#!/bin/bash

url=$1
path=$2/bartixxx-mirror

echo "Starting archiving!"

youtube-dl $url \
--download-archive $path/downloaded.txt \
-o "$path/bartixxx-mirror/%(uploader)s/%(upload_date)s - %(title)s/%(uploader)s - %(title)s - %(upload_date)s %(id)s.%(ext)s" \
-f bestvideo+bestaudio \
--merge-output-format mkv \
--write-thumbnail \
--write-description \
--write-info-json \
--write-annotations \
--all-subs

echo "Archiving done!"
